name: Test actionsSampleDemo
on: push

jobs:
  testActionsDemo:
    name: Test First Action Demo
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: dwarak72TR/actionsCreationSample@main
        with:
            appid: "1278324"
            api_call_name: "getbuildinfo"        
            vid: "id"
            vkey: "key"
            
     