name: Veracode Scanning Process for NGOTP
on: push

env: 
  VERACODE_API_ID: ${{secrets.VERACODE_API_ID}}
  VERACODE_API_KEY: ${{secrets.VERACODE_API_TOKEN}}
  application_id: ${{ 1275652 }}

jobs:
  veracodeScoreRetrieve:
    name: veracode Scan Score Retrieve
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
            
      - name: Download Jar Files
        run: |  
            sudo apt install unzip            
            wget "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/18.9.5.4/vosp-api-wrappers-java-18.9.5.4-dist.zip"
            unzip vosp-api-wrappers-java-18.9.5.4-dist.zip -d $GITHUB_WORKSPACE/veracode
            cd veracode                   
            wget "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2.jar"   
            ls -lrt         
            
      - name: Get Build Id and Summary report
        run: |
            java -jar $GITHUB_WORKSPACE/veracode/vosp-api-wrappers-java-21.9.8.2.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} -action getbuildinfo -appid ${application_id} > output.xml 
            ls -lrt
           
            BUILD_id=$(python c "print("Hellow man")")          
            echo "Build_id= $BUILD_id"
            java -jar $GITHUB_WORKSPACE/veracode/VeracodeJavaAPI.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} -action summaryreport -buildid $BUILD_id -outputfilepath $GITHUB_WORKSPACE/summaryreport.xml
            score=$(python $GITHUB_WORKSPACE/scripts/veracode_score.py)
            echo "score is $score"

          
          

