name: Veracode Scanning Process for NGOTP
on: push

env: 
  VERACODE_API_ID: ${{secrets.VERACODE_API_ID}}
  VERACODE_API_KEY: ${{secrets.VERACODE_API_TOKEN}}

jobs:
  veracodeScoreRetrieve:
    name: veracode Scan Score Retrieve
    runs-on: ubuntu-latest
    steps:    
      - name: Download Jar Files
        run: |
            wget "curl -O https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2-dist.zip"
            echo "pwd"
          

