name: Veracode Scanning Process for NGOTP
on: push

env: 
  VERACODE_API_ID: ${{secrets.VERACODE_API_ID}}
  VERACODE_API_KEY: ${{secrets.VERACODE_API_TOKEN}}
  applicationid: 1275632

  

jobs:
  VeracodeObtainScore:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: SetUp Version
        run: date

      - name: Download Jar Files
        run: "curl -O https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2.jar"
      
      - name: Obtain Test Score Results
        run: |
          "java -jar $WORKSPACE\\veracode\\vosp-api-wrappers-java-21.9.8.2.jar -vid ${env.VERACODE_API_ID} -vkey ${env.VERACODE_API_KEY} -action getbuildinfo -appid ${env.applicationid} > output.xml"
          "cat output.xml"
      