name: Veracode Scanning Process for NGOTP
on: push

env: 
  VERACODE_API_ID: ${{secrets.VERACODE_API_ID}}
  VERACODE_API_KEY: ${{secrets.VERACODE_API_TOKEN}}
  application_id: ${{ 1275655 }}

jobs:
  veracodeScoreRetrieve:
    name: veracode Scan Score Retrieve
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
            
      - name: Download Jar Files
        run: |            
            wget "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2.jar"            
            
      - name: Get Build Info
        run: |
            java -jar $GITHUB_WORKSPACE/vosp-api-wrappers-java-21.9.8.2.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY} -action getbuildinfo -appid ${application_id} > output.xml 
            cat output.xml  
            output=$(python $GITHUB_WORKSPACE/scripts/veracodelib.py)
            echo "$output"

          
          

